#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S3,     HTCS,                sensorLowSpeed)
#pragma config(Sensor, S2,     colorPort,           sensorCOLORFULL)
#pragma config(Motor,  motorA,          ,              tmotorNormal, openLoop, encoder)
#pragma config(Motor,  motorB,          ,              tmotorNormal, openLoop, encoder)
#pragma config(Motor,  motorC,          ,              tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorsLeft,    tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorsRight,   tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorArm,      tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "drivers/common.h"
#include "drivers/HTCS-driver.h"

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}

float forward(float dist, float wheelRadius)
{
  float Pie = 3.14159;
  return (1440*dist)/(2*Pie*wheelRadius);
}

float turn(float wheelRadius, float distBtwnWheels, float degreesToTurn)
{
  return ((4*degreesToTurn*distBtwnWheels)/wheelRadius)/2;
}

void makeFD(float dist, int power, float wR, float dBW)
{
  //int powerCompensation = (power*27)/50;
  int powerCompensation = power;
  dist = dist * 24;
  nMotorEncoder[motorsLeft] = 0;
  nMotorEncoder[motorsRight] = 0;

  motor[motorsRight] = power;
  motor[motorsLeft] = powerCompensation;

  while(nMotorEncoder[motorsLeft] < forward(dist, wR)) {}

  motor[motorsLeft] = 0;
  motor[motorsRight] = 0;
  wait1Msec(500);
}

void makeRight(float degrees, float power, float wR, float dBW)
{
  degrees = degrees * 90;
  power = power * 25;
  nMotorEncoder[motorsLeft] = 0;
  nMotorEncoder[motorsRight] = 0;

  motor[motorsLeft] = power;
  motor[motorsRight] = -power;

  while(nMotorEncoder[motorsLeft] < turn(wR, dBW, degrees)) {}

  motor[motorsLeft] = 0;
  motor[motorsRight] = 0;

  wait1Msec(500);
}

void makeLeft(float degrees, float power, float wR, float dBW)
{
  degrees = degrees * 90;
  power = power * 25;
  nMotorEncoder[motorsLeft] = 0;
  nMotorEncoder[motorsRight] = 0;

  motor[motorsLeft] = -power;
  motor[motorsRight] = power;

  while(nMotorEncoder[motorsLeft] > -turn(wR, dBW, degrees)) {}

  motor[motorsLeft] = 0;
  motor[motorsRight] = 0;

  wait1Msec(500);
}

task main()
{
  initializeRobot();
  //waitForStart();
  float wR = 2;
  float dBW = 17.5;
  int red = 0;
  int green = 0;
  int blue = 0;
  int _color = 0;
  int _colorindex = 0;
  string _tmp;
  int val = 255;

  nMotorEncoder[motorsLeft] = 0;
  nMotorEncoder[motorsRight] = 0;

  //makeFD(1.42, 100, wR, dBW);
  //makeLeft(.5, 15, wR, dBW);

  //makeFD(1.45, 25, wR, dBW);
  //makeRight(.9, 10, wR, dBW);

  nMotorEncoder[motorsLeft] = 0;
  nMotorEncoder[motorsRight] = 0;

  HTCSreadRGB(HTCS, red, green, blue);
  while((red + green + blue) < 600/* || nMotorEncoder[motorsLeft] < forward(30, wR)*/)
  {
    HTCSreadRGB(HTCS, red, green, blue);
    motor[motorsLeft] = 10;
    motor[motorsRight] = 10;
  }

  for(int i = 5; i == 0; i = i - 1)
  {
    motor[motorsRight] = i;
    motor[motorsLeft] = i;
    wait1Msec(10 * (6 - i));
  }

  // </gradual slowing>

  motor[motorsLeft] = 0;
  motor[motorsRight] = 0;

  wait1Msec(1500);

  motor[motorArm] = -40;
  wait1Msec(700);
  motor[motorArm] = 0;

  wait1Msec(1000);

  motor[motorArm] = 15;
  wait1Msec(650);
  motor[motorArm] = 0;

  // </lift and lower>


}
