#pragma config(Hubs,  S4, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     GyroSensor,          sensorNone)
#pragma config(Sensor, S2,     colorPort,           sensorCOLORFULL)
#pragma config(Sensor, S3,     HTCS,                sensorI2CCustom)
#pragma config(Motor,  motorA,          ,              tmotorNormal, openLoop, encoder)
#pragma config(Motor,  motorB,          ,              tmotorNormal, openLoop, encoder)
#pragma config(Motor,  motorC,          ,              tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S4_C1_1,     motorD,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S4_C1_2,     motorE,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S4_C2_1,     motorF,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S4_C2_2,     motorG,        tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Sensor, S1,     msensor_S2_1,              sensorLowSpeed)


#include "JoystickDriver.c"
#include "drivers/common.h"
#include "drivers/HTGYRO-driver.h"

task main()
{
  	//Calibrate with
	HTGYROstartCal(GyroSensor);
	int movementValid = 1;
	float gyroValue;
	float summationAngle = 0;
	while(movementValid == 1)
	{
	  motor[motorB] = 30;
	  motor[motorC] = -30;
	  HTGYROstartCal(GyroSensor);
	  gyroValue = HTGYROreadRot(GyroSensor);
		summationAngle += gyroValue;
		if(summationAngle > 89)
		{
		  movementValid = 0;
		}
  	wait1Msec(4);
	}
//	PlaySound(soundFastUpwardTones);
}

//1.2 == 93
//
