#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorArm,      tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorNormal, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

//Version 1.3

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}

task main()
{
  initializeRobot();
  //waitForStart();

  int threshold = 10;             /* Int 'threshold' will allow us to ignore low       */
  float sensetivity = 1;
  int ud = 1;
  int fix = 1;

  while(true)                            // Infinite loop:
  {
    if(joy1Btn(1)) {sensetivity = 1.2; }
    if(joy1Btn(2)) {sensetivity = .1; }
    if(joy1Btn(3)) {sensetivity = 4.0; }

    getJoystickSettings(joystick);
    if(abs(joystick.joy1_y1) > threshold)   // If the right analog stick's Y-axis readings are either above or below the threshold:
    {
      motor[motorD] = joystick.joy1_y1 / (2*sensetivity);         // Motor B is assigned a power level equal to the right analog stick's Y-axis reading.
    }
    else                                    // Else if the readings are within the threshold:
    {
      motor[motorD] = 0;                        // Motor B is stopped with a power level of 0.
    }


    if(abs(joystick.joy1_y1) > threshold)   // If the left analog stick's Y-axis readings are either above or below the threshold:
    {
      motor[motorE] = joystick.joy1_y1 / (2*sensetivity);         // Motor C is assigned a power level equal to the left analog stick's Y-axis reading.
    }
    else                                    // Else if the readings are within the threshold:
    {
      motor[motorE] = 0;                        // Motor C is stopped with a power level of 0.
    }

    if(abs(joystick.joy1_x1) > threshold)
    {
      motor[motorE] -= joystick.joy1_x1 / (2*sensetivity);
      motor[motorD] += joystick.joy1_x1 / (2*sensetivity);

      if(abs(joystick.joy1_y1) < 30)
      {
        if(joystick.joy1_x1 < 0)
        {
          motor[motorE] = (100/sensetivity);
          motor[motorD] = (-100/sensetivity);
        }
        else
        {
          motor[motorE] = (-100/sensetivity);
          motor[motorD] = (100/sensetivity);
        }
      }
    }
      if (joy1Btn(6))
      {
        motor[motorC] = 20;
        motor[motorB] = 20;
      }
      else
      {
        motor[motorC] = 0;
        motor[motorB] = 0;
      }

      if (joy1Btn(8))
      {
        motor[motorB] = -20;
        motor[motorC] = -20;
        wait1Msec(200);
      }
      if(joy1Btn(5))
      {
        if(ud == 1)
        {
          ud = 0;
          fix = 0;
          motor[motorArm] = -50;
          wait1Msec(700);
          motor[motorArm] = 0;
        }
      }
      if(joy1Btn(4))
      {
        if (fix == 0)
        {
          fix = 1;
          motor[motorArm] = 8;
          wait1Msec(100);
          motor[motorArm] = 0;
        }
      }

      if(joy1Btn(7))
      {
        if(ud == 0)
        {
          ud = 1;
          motor[motorArm] = 15;
          wait1Msec(650);
          motor[motorArm] = 0;
        }
      }
}
  wait1Msec(100);
}
