#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,                    sensorI2CMuxController)
#pragma config(Sensor, S2,     ,                    sensorI2CMuxController)
#pragma config(Motor,  motorA,          motorArmTurn,  tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorF,        tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorArm1,     tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorArm3,     tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorArm2,     tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motorArmFlappyThing, tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorK,        tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S2_C1_1,     motorRight,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_2,     motorLeft,     tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servoRot,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "ButtonControl.c"
#include "DriveTrainControl.c"

//To Do:
//  0) Go through tweaks for        liftArm        /BCom.h
//  1) Calibrate arm clamp          initRbt        /ManCodeNI.c
// *2) Set motor polarizations      #pragma        /MCNI.c
//  3) Adjust speed in              rotateClamp    /BCom.h
//  4) Set motor polarization in    liftArm        /BCom.h
//  5) Set polarization of          controlArmTilt /BCom.h
//  6) Lay out button control map   buttonControl  /BCon.h
//  7) Set target for 90deg rot     rotateClamp    /BCom.h
//  8) Set init targets for         initRbt        /AutoTemplate.c
//  9) Link control functions
//      -Sensitivity adj.
//      -Crate rotation
//      -Crate clamp open/close + POLAR
//  A) Set polar of dpad ctrl       controlArmTilt /BCom.h

/*
Polarizations:
Arm motors: positive raises
Rotate crate: positve ccw
Clamp motor: positive inwards
*/

/*
  To Do:
    1) Verify core functions (button registering, etc.)
    2) rootnoverify polarizations:
      -Motors (pragma)/MCNI.c
      -Clamp open+close/BCon.h
      -controlArmTilt/DTCon.h (2x)
      -Sensitivity toggle/BCon.h
      -Rotate clamp polar/BCom.h
      -Flipping arm/BCon.h
    3) Test functions
      -btn()/BCom.h
      -Auto init robot
      -rotateClamp180()/BCom.h
      -rotateClamp90()/BCom.h
      -liftArm()/BCom.h
      -controlArmTilt()/DTCon.h

*/

//bool rotationLock = false;

/*task mon()
{
  //motor[motorA] = stupidRobotCDoesntWork;
  int scalar = 1;
  float servoDegConv = 255/180;
  while(true)
  {
    servo[servoRot] = 165-servoDegConv*scalar*angleArmFlappyThingy;
    nxtDisplayTextLine(4, ""+angleArmFlappyThingy);
    nxtDisplayTextLine(3, ""+servo[servoRot]);

    //float tmpVal = (angleVal2 - angleVal3) + angleValTurn;
	  //if(!rotationLock && abs(tmpVal) > 5)
	  //{
	  //  mArmTurn = 40*abs(tmpVal)/tmpVal;
	  //}

    EndTimeSlice();
  }
}*/

void initializeRobot()
{
  /*motor[motorArmFlappyThingy] = -10;*/
  mArm1 = 0;
  mArm2 = 0;
  mArm3 = 0;
  mArmFlappyThing = 0;
  mArmTurn = 0;
  //artTask(mon);
}

//#ifndef angleArmFlappy

task main()
{
  initializeRobot();
  //waitForStart();
  while(true)
  {
    float servoDegConv = 255/180;
    servo[servoRot] = 165-servoDegConv*angleArmFlappyThingy;

    //nxtDisplayTextLine(6, ""+mArmTurn);
    driveTrainControl();
    buttonControl();

		/*float aV1=((nMotorEncoder[motorArm1]/4)/27);
		float aV2=((nMotorEncoder[motorArm2]/4)/9);
		float aV3=((nMotorEncoder[motorArm3]/4)/9);
		float aVTurn=((nMotorEncoder[motorArmTurn]/3)/1);

		float thing = abs(aV2) + abs(aV3) - abs(aVTurn);
		nxtDisplayTextLine(6, ""+thing);
    if(abs(thing) > 5)
    {
      int hi = abs(thing)/thing;
      motor[motorArmTurn] = hi*15;
    }
    else
    {
      if(btn(6) || btn(7)) {} else {motor[motorArmTurn] = 0;}
    }*/
    //if(enableControlSwitch) switchControls();
  }
}
