#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,                    sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorLeft,     tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorRight,    tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorArm1,     tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorArm2,     tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motorArm3,     tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorArmTurn,  tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     motorArmFlappyThingy, tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     motorK,        tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define enterPressed (nNxtButtonPressed == 3)
#define leftPressed (nNxtButtonPressed == 2)
#define rightPressed (nNxtButtonPressed == 1)

task main()
{
  int currentMotor = 1;
  while(true)
  {
    if(currentMotor == 0) currentMotor = 5;
    if(currentMotor == 6) currentMotor = 1;
    if(currentMotor == 1) {nxtDisplayTextLine(2, "[X]: Arm1");} else {nxtDisplayTextLine(2, "[ ]: Arm1");}
    if(currentMotor == 2) {nxtDisplayTextLine(3, "[X]: Arm2");} else {nxtDisplayTextLine(3, "[ ]: Arm2");}
    if(currentMotor == 3) {nxtDisplayTextLine(4, "[X]: Arm3");} else {nxtDisplayTextLine(4, "[ ]: Arm3");}
    if(currentMotor == 4) {nxtDisplayTextLine(5, "[X]: MRot");} else {nxtDisplayTextLine(5, "[ ]: MRot");}
    if(currentMotor == 5) {nxtDisplayTextLine(6, "[X]: MCrunch");} else {nxtDisplayTextLine(6, "[ ]: MCrunch");}
    if(leftPressed) currentMotor -= 1;
    if(rightPressed) currentMotor += 1;

  }
}
