#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     motorsLeft,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorsRight,   tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorArm,      tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorNormal, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

//Version 1.3

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}

task main()
{
  initializeRobot();

  int movementSensetivity = 1;
  int movementThreshold = 10;

  while(true)
  {
    getJoystickSettings(joystick);
    float motorsLeftPower = 0;
    float motorsRightPower = 0;

    float forwardSpeed = joystick.joy1_y1/movementSensetivity*100/128;

    if(abs(forwardSpeed) > movementThreshold)
    {
      motorsLeftPower = forwardSpeed;
      motorsRightPower = forwardSpeed;
    }
    else
    {
      motorsLeftPower = 0;
      motorsRightPower = 0;
    }

    if(abs(joystick.joy1_x1) > movementThreshold)
    {
      motorsLeftPower += joystick.joy1_x1/4;
      motorsRightPower -= joystick.joy1_x1/4;
    }

    motor[motorsLeft] = motorsLeftPower;
    motor[motorsRight] = motorsRightPower;
  }
}
