#pragma config(Hubs,  S4, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     SMUX,           sensorI2CCustom)
#pragma config(Sensor, S2,     sGyr,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     sAcc,           sensorI2CCustomFastSkipStates)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S4_C1_1,     motorBL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_2,     motorFL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_1,     motorAmrL,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S4_C2_2,     motorAmrR,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S4_C3_1,     motorBR,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S4_C3_2,     motorFR,       tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "AccelGyroDriver.h"
#include "AutoHolonomic.h"
#include "ArmControl2.h"
#include "drivers/hitechnic-sensormux.h"
#include "drivers/hitechnic-irseeker-v2.h"
#include "JoystickDriver.c"

int cols[3] = {0,0,0};
void getIRColumnTargetData() {
	for(int col=0; col<3; col++) {
		int row = 0;
		while(nNxtButtonPressed != 3) {
			nxtDisplayTextLine(2+col, "IR Col %d ==> R%d", col+1, row);
			if(nNxtButtonPressed == 1) {row++; while(nNxtButtonPressed == 1){}}
			if(nNxtButtonPressed == 2) {row--; while(nNxtButtonPressed == 2){}}
			if(row > 3) row = 1; if(row < 1) row = 3;
		}
		cols[col] = row;
		PlaySound(soundShortBlip);
		while(nNxtButtonPressed == 3){}
	}
}

int getIRColumn() {
	int x = -1;
	ClearTimer(T4);
	while(x == -1 && time1(T4) < 5000) {
		int col1 = HTIRS2readACDir(msensor_S1_1);
		int col2 = HTIRS2readACDir(msensor_S1_2);
		nxtDisplayTextLine(3, "%i, %i", col1, col2);
		if(col1 == 3 && (col2 == 7 || col2 == 9)) x = 3;
		if(col1 == 2) x = 2;
		if((col1 == 0 || col1 == 1) && (col2 == 0 || col2 == 7)) x = 1;
		nxtDisplayTextLine(4, "%i", x);
	}
	return (x==-1?3:x);
}

void sPaws(int msec) {
	ClearTimer(T1);
	while(time1[T1] < msec) EndTimeSlice();
}

void autoCol1() {
	//StartTask(armMid);
	moveToWhite(0, 1, .75);
	moveToRot(10);
	moveToPos(-.5, 0, .5);
	moveToRot(18);
	//moveToWhite(0, 1, .3);)
	sPaws(500);

	moveToPos(0, 1.5, 1);
	motor[motorAmrL] = -65;
 	motor[motorAmrR] = -65;
	ClearTimer(T1); while(time1[T1] < 1000){EndTimeSlice();}
	motor[motorAmrL] = 0;
 	motor[motorAmrR] = 0;
	moveToPos(0, -1.5, 1);
}

void autoCol2() {
	moveToWhite(0, 1, .7);

	//targetMag = 0.5;
	//targetTh = 0;
	//ClearTimer(T1); while(time1[T1] < 300){EndTimeSlice();}
	//targetMag = 0.0;

	moveToRot(72);
	//robotRot = 0;
	sPaws(1000);

	moveToPos(0, 1.2, 1);
	motor[motorAmrL] = -50;
 	motor[motorAmrR] = -50;
	ClearTimer(T1); while(time1[T1] < 500){EndTimeSlice();}
	moveToPos(0, -1, 1);
	ClearTimer(T1); while(time1[T1] < 250){EndTimeSlice();}
	motor[motorAmrL] = -0;
 	motor[motorAmrR] = -0;
}

void autoCol3() {
	moveToWhite(0, 1, .75);
	moveToPos(0, -.41, .5);
	moveToRot(122);
	sPaws(2000);

	moveToPos(0, 2.5, 1);
	motor[motorAmrL] = -20;
 	motor[motorAmrR] = -20;
	ClearTimer(T1); while(time1[T1] < 1000){EndTimeSlice();}
	moveToPos(0, -3, 1);
	ClearTimer(T1); while(time1[T1] < 500){EndTimeSlice();}
	motor[motorAmrL] = 0;
	motor[motorAmrR] = 0;
	robotRot = 0;
	moveToRot(-30);
}

void initializeRobot() {

	nMotorEncoder[motorAmrL] = 0; nMotorEncoder[motorAmrR] = 0;
	//getIRColumnTargetData();
	nxtDisplayTextLine(6, "LOCKED");

	debugAccelGyro = false;
	waitForStart();
	BackgroundIntegration();
	StartTask(HolonomicControl);
}

void closeAutonomous() {

}

task main() {
	initializeRobot();
	//StartTask(armHi);
	/*StartTask(armMid); autoCol2();
	int irCol = getIRColumn();
	/*nxtDisplayTextLine(6, "%i", irCol);
	if(irCol == 1) {StartTask(armHi); autoCol3();}
	if(irCol == 2) {StartTask(armMid); autoCol2();}
	if(irCol == 3) {StartTask(armHi); autoCol3();}*/
	StartTask(armMid); autoCol2();
	ClearTimer(T1); while(time1[T1] < 10000){EndTimeSlice();}
	closeAutonomous();
}
