#pragma config(Hubs,  S4, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     SMUX,           sensorI2CCustom)
#pragma config(Sensor, S2,     sGyr,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     sAcc,           sensorI2CCustomFastSkipStates)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S4_C1_1,     motorBL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_2,     motorFL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_1,     motorArmE2,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S4_C2_2,     motorArms,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S4_C3_1,     motorBR,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S4_C3_2,     motorFR,       tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	motor[motorArms] = -100;
	wait1Msec(15);
	motor[motorArms] = -7;
	int mPow = -3;
	while(!(nNxtButtonPressed == 3)) {
		//motor[motorArms] = mPow;
		//if(nNxtButtonPressed == 1) mPow--;
		//if(nNxtButtonPressed == 2) mPow++;
		nxtDisplayTextLine(3, "%i", motor[motorArms]);
		//while(nNxtButtonPressed == 1 || nNxtButtonPressed == 2);
	}
}
