#pragma config(Hubs,  S4, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     SMUX,           sensorI2CCustom)
#pragma config(Sensor, S2,     sGyr,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     sAcc,           sensorI2CCustomFastSkipStates)
#pragma config(Motor,  mtr_S4_C1_1,     mBLz,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_2,     mFLz,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_1,     mArm,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C3_1,     mBRz,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C3_2,     mFRz,          tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "AccelGyroDriver.h"

task main()
{
	BackgroundIntegration();
	while(true) {
		wait1Msec(10);
		//nxtDisplayTextLine(6, "lasif: %f", SensorValue[sAcc]);
		//int xAcc, yAcc, zAcc;
		//HTACreadAllAxes(sAcc, xAcc, yAcc, zAcc);
		//nxtDisplayTextLine(6, "sf: %f", yAcc);
		EndTimeSlice();
	}
}
