#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S2,     sGyr,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     sAcc,           sensorI2CHiTechnicAccel)
#pragma config(Sensor, S4,     SMUX,              sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     mBLz,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     mFLz,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     mArm,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     mBRz,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     mFRz,          tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "MovementInterfaceDriver.h"
#include "DualSmuxIRDriver.h"

/*
	[*](x,y,z)Off = (x,y,z) accelerometer offset
	[*](x,y,z)Scl = (x,y,z) accelerometer scalar
	[*](x,y,z)AccAvg[5] = (x,y,z) acceleration average array
	[*]gVal = gyroscopic value
	[*]lastIterTime = time of last iteration
	[*]aToN = acceleration to newtons conversion
	[*]aThresh = acceleration threshold
	[*]gyrThresh = gyroscope threshold

	[R](x,y,z)Pos = (x,y,z) postion offset
	[R](x,y,z)Vel = (x,y,z) velocity
	[R](x,y,z)Acc = (x,y,z) acceleration
	[R]robotTh = robot theta

	[W]targetRobotTh = target robot angle
	[W]targetMoveTh = target robot movement direction
	[W]targetMoveMag = movement magnitude for robot

	[D]accSensor = acceleration sensor port
	[D]gyrSensor = gyroscope sensor port
	[D]m(Back,Front)(Right,Left) = motors

	[F]setupMotors(mBL, mFR, mBR, mFL) = sets up motors for HolonomicControl
	[F]setupSensors(snsAcc, snsGyr) = sets up sensors for BackgroundIntegration
	[F]setAccuracy(mov, rot) = sets up accuracy for movement
	[F]moveTo(x,y,m) = moves to location (x,y) with mag (m)
	[F]moveToTh(th) = moves to theta

	[T]BackgroundIntegration = the background integrator task for accel/gyro
	[T]HolonomicControl = background control for holonomic drive

	[*] = for internal use only
	[R] = for reading only
	[W] = for writing only
	[D] = mandatory define statements
	[F] = mandatory function calls
	[T] = tasks
*/

int cols[3] = {0,0,0};

void getIRColumnTargetData() {
	for(int col=0; col<3; col++)
	{
		int row = 0;
		while(nNxtButtonPressed != 3) {
			nxtDisplayTextLine(3+col, "IR Col %d ==> R%d", col, row);
		}
		cols[col] = row;
	}
}

void initializeRobot() {
	getIRColumnTargetData();
	setupMotors(mBLz, mFRz, mBRz, mFLz);
	setupAccGyr(sAcc, sGyr);
	setupIRSmux(msensor_S1_1, msensor_S1_2);
	setDriveAccuracy(.5, 3);

	StartTask(BackgroundIntegration);
	StartTask(HolonomicControl);
}

task main()
{
	initializeRobot();
	//waitForStart();
	int col = findIRColumn();
	int row = cols[col];
	row = row;

	moveToPos(0, 1, .5);
	moveToTh(45);
	moveToPos(1, 0, .5);
	moveToPos(.75, .75, .5);
}
