#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Motor,  motorA,          ,              tmotorNormal, openLoop, encoder)
#pragma config(Motor,  motorB,          ,              tmotorNormal, openLoop, encoder)
#pragma config(Motor,  motorC,          ,              tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorsLeft,    tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorsRight,   tmotorNormal, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float forward(float dist, float wheelRadius)
{
  float Pie = 3.14159;
  return (1440*dist)/(2*Pie*wheelRadius);
}

float turn(float wheelRadius, float distBtwnWheels, float degreesToTurn)
{
  return ((4*degreesToTurn*distBtwnWheels)/wheelRadius)/2;
}

void makeFD(int dist, int power, float wR, float dBW)
{
  nMotorEncoder[motorsLeft] = 0;
  nMotorEncoder[motorsRight] = 0;

  nMotorEncoderTarget[motorsLeft] = forward(dist, wR);
  nMotorEncoderTarget[motorsRight] = forward(dist, wR);

  motor[motorsRight] = power;
  motor[motorsLeft] = power;
}

void makeRight(int degrees, int power, float wR, float dBW)
{
  nMotorEncoder[motorsLeft] = 0;
  nMotorEncoder[motorsRight] = 0;

  nMotorEncoderTarget[motorsLeft] = turn(wR, dBW, degrees);
  nMotorEncoderTarget[motorsRight] = -turn(wR, dBW, degrees);

  motor[motorsLeft] = power;
  motor[motorsRight] = -power;
}

void makeLeft(int degrees, int power, float wR, float dBW)
{
  nMotorEncoder[motorsLeft] = 0;
  nMotorEncoder[motorsRight] = 0;

  nMotorEncoderTarget[motorsLeft] = -turn(wR, dBW, degrees);
  nMotorEncoderTarget[motorsRight] = turn(wR, dBW, degrees);

  motor[motorsLeft] = -power;
  motor[motorsRight] = power;
}

task main()
{
  float wR = 2;
  float dBW = 16;
  nMotorEncoder[motorsLeft] = 0;
  nMotorEncoder[motorsRight] = 0;

  makeFD(96, 100, wR, dBW);
  wait1Msec(3000);
}
