#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorArm,      tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorNormal, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

//Version 1.3

void senseSound(float s)
{
  if(s == 1.2) {PlayTone(250, 55); while(bSoundActive);}
  if(s == 2) {PlayTone(500, 55); while(bSoundActive);}
  if(s == 4) {PlayTone(750, 55); while(bSoundActive);}
  if(s == 8) {PlayTone(1000, 55); while(bSoundActive);}
}
void starwars()
{
PlayTone(695, 14); while(bSoundActive);
PlayTone(695, 14); while(bSoundActive);
PlayTone(695, 14); while(bSoundActive);
PlayTone(929, 83); while(bSoundActive);
PlayTone(1401, 83); while(bSoundActive);
PlayTone(1251, 14); while(bSoundActive);
PlayTone(1188, 14); while(bSoundActive);
PlayTone(1054, 14); while(bSoundActive);
PlayTone(1841, 83); while(bSoundActive);
PlayTone(1401, 41); while(bSoundActive);
PlayTone(1251, 14); while(bSoundActive);
PlayTone(1188, 14); while(bSoundActive);
PlayTone(1054, 14); while(bSoundActive);
PlayTone(1841, 83); while(bSoundActive);
PlayTone(1401, 41); while(bSoundActive);
PlayTone(1251, 14); while(bSoundActive);
PlayTone(1188, 14); while(bSoundActive);
PlayTone(1251, 14); while(bSoundActive);
PlayTone(1054, 55); while(bSoundActive);
wait1Msec(280);
PlayTone(695, 14); while(bSoundActive);
PlayTone(695, 14); while(bSoundActive);
PlayTone(695, 14); while(bSoundActive);
PlayTone(929, 83); while(bSoundActive);
PlayTone(1401, 83); while(bSoundActive);
PlayTone(1251, 14); while(bSoundActive);
PlayTone(1188, 14); while(bSoundActive);
PlayTone(1054, 14); while(bSoundActive);
PlayTone(1841, 83); while(bSoundActive);
PlayTone(1401, 41); while(bSoundActive);
PlayTone(1251, 14); while(bSoundActive);
PlayTone(1188, 14); while(bSoundActive);
PlayTone(1054, 14); while(bSoundActive);
PlayTone(1841, 83); while(bSoundActive);
PlayTone(1401, 41); while(bSoundActive);
PlayTone(1251, 14); while(bSoundActive);
PlayTone(1188, 14); while(bSoundActive);
PlayTone(1251, 14); while(bSoundActive);
PlayTone(1054, 55); while(bSoundActive);
}

task main()
{
  starwars();
  int i;
  int threshold = 10;             /* Int 'threshold' will allow us to ignore low       */
  float sensetivity = 1;
  int ud = 1;
  // servoChangeRate[servo1] = 30;                                /* readings that keep our robot in perpetual motion. */
  //starwars();

  while(true)                            // Infinite loop:
  {
    if(joy1Btn(1)) {sensetivity = 1.2; senseSound(sensetivity);}
    if(joy1Btn(2)) {sensetivity = 2; senseSound(sensetivity);}
    if(joy1Btn(3)) {sensetivity = 4; senseSound(sensetivity);}
    if(joy1Btn(4)) {sensetivity = 8; senseSound(sensetivity);}
    getJoystickSettings(joystick);
    if(abs(joystick.joy1_y1) > threshold)   // If the right analog stick's Y-axis readings are either above or below the threshold:
    {
      motor[motorD] = joystick.joy1_y1 / (2*sensetivity);         // Motor B is assigned a power level equal to the right analog stick's Y-axis reading.
    }
    else                                    // Else if the readings are within the threshold:
    {
      motor[motorD] = 0;                        // Motor B is stopped with a power level of 0.
    }


    if(abs(joystick.joy1_y1) > threshold)   // If the left analog stick's Y-axis readings are either above or below the threshold:
    {
      motor[motorE] = joystick.joy1_y1 / (2*sensetivity);         // Motor C is assigned a power level equal to the left analog stick's Y-axis reading.
    }
    else                                    // Else if the readings are within the threshold:
    {
      motor[motorE] = 0;                        // Motor C is stopped with a power level of 0.
    }

    if(abs(joystick.joy1_x1) > threshold)
    {
      motor[motorE] -= joystick.joy1_x1 / (2*sensetivity);
      motor[motorD] += joystick.joy1_x1 / (2*sensetivity);

      if(abs(joystick.joy1_y1) < 30)
      {
        if(joystick.joy1_x1 < 0)
        {
          motor[motorE] = (100/sensetivity);
          motor[motorD] = (-100/sensetivity);
        }
        else
        {
          motor[motorE] = (-100/sensetivity);
          motor[motorD] = (100/sensetivity);
        }
      }
    }
      if (joy1Btn(6))
      {
        //nMotorEncoder[motorC] = 0;
        //nMotorEncoderTarget[motorC] = 360;
        motor[motorC] = 20;
        //nMotorEncoder[motorB] = 0;
        //nMotorEncoderTarget[motorB] = 360;
        motor[motorB] = 20;
      }
      else
      {
        motor[motorC] = 0;
        motor[motorB] = 0;
      }

      if (joy1Btn(8))
      {
        motor[motorB] = -20;
        motor[motorC] = -20;
        wait1Msec(200);
      }

      if(joy1Btn(5))
      {
        if(ud == 1)
        {
          ud = 0;
          //senseSound(1);
          motor[motorArm] = -30;
          wait1Msec(840);
          motor[motorArm] = 0;
        }
      }

      if(joy1Btn(7))
      {
        if(ud == 0)
        {
          ud = 1;
          //senseSound(4);
          motor[motorArm] = 15;
          wait1Msec(575);
          motor[motorArm] = 0;
        }
      }
}
  wait1Msec(100);
}
