#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Motor,  motorA,          motor,         tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorG,        tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorF,        tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

//Version 1.3

void senseSound(int s)
{
  if(s == 1) {PlayTone(250, 55); while(bSoundActive);}
  if(s == 2) {PlayTone(500, 55); while(bSoundActive);}
  if(s == 4) {PlayTone(750, 55); while(bSoundActive);}
  if(s == 8) {PlayTone(1000, 55); while(bSoundActive);}
}

task main()
{
  int threshold = 10;             /* Int 'threshold' will allow us to ignore low       */
  float sensetivity = 1;

  // servoChangeRate[servo1] = 30;                                /* readings that keep our robot in perpetual motion. */

  while(true)                            // Infinite loop:
  {
    if(joy1Btn(1)) {sensetivity = 1; senseSound(sensetivity);}
    if(joy1Btn(2)) {sensetivity = 2; senseSound(sensetivity);}
    if(joy1Btn(3)) {sensetivity = 4; senseSound(sensetivity);}
    if(joy1Btn(4)) {sensetivity = 8; senseSound(sensetivity);}
    getJoystickSettings(joystick);
    if(abs(joystick.joy1_y1) > threshold)   // If the right analog stick's Y-axis readings are either above or below the threshold:
    {
      motor[motorD] = joystick.joy1_y1 / (2*sensetivity);         // Motor B is assigned a power level equal to the right analog stick's Y-axis reading.
    }
    else                                    // Else if the readings are within the threshold:
    {
      motor[motorD] = 0;                        // Motor B is stopped with a power level of 0.
    }


    if(abs(joystick.joy1_y1) > threshold)   // If the left analog stick's Y-axis readings are either above or below the threshold:
    {
      motor[motorE] = joystick.joy1_y1 / (2*sensetivity);         // Motor C is assigned a power level equal to the left analog stick's Y-axis reading.
    }
    else                                    // Else if the readings are within the threshold:
    {
      motor[motorE] = 0;                        // Motor C is stopped with a power level of 0.
    }

    if(abs(joystick.joy1_x1) > threshold)
    {
      motor[motorE] -= joystick.joy1_x1 / (2*sensetivity);
      motor[motorD] += joystick.joy1_x1 / (2*sensetivity);

      if(abs(joystick.joy1_y1) < 30)
      {
        if(joystick.joy1_x1 < 0)
        {
          motor[motorE] = (100/sensetivity);
          motor[motorD] = (-100/sensetivity);
        }
        else
        {
          motor[motorE] = (-100/sensetivity);
          motor[motorD] = (100/sensetivity);
        }
      }
      if (joy1Btn(6))
      {
        nMotorEncoderTarget[motorF] = 0;
        nMotorEncoderTarget[motorF] = 360;
        motor[motorF] = 100;
        wait1Msec(5000);
      }
      if (joy1Btn(5))
      {
        motor[motorA] = 40;
      }

}

  /*nMotorEncoder[motorC] = 0;
  nMotorEncoderTarget[motorC] = 360*11;

  wait1Msec(10000);*/
  wait1Msec(100);
  }
}
