#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{
  int buttonP;
  while(1 == 1)
  {
    if(joy1Btn(1)) {motor[motorC] = 30;}
    if(joy1Btn(2)) {motor[motorC] = 40;}
    if(joy1Btn(3)) {motor[motorC] = 50;}
    if(joy1Btn(4)) {motor[motorC] = 60;}
    if(joy1Btn(5)) {motor[motorC] = 70;}
    if(joy1Btn(6)) {motor[motorC] = 80;}
    if(joy1Btn(7)) {motor[motorC] = 90;}
    if(joy1Btn(8)) {motor[motorC] = 100;}

 }
}
