#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    ,                     tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{
  int threshold = 10;             /* Int 'threshold' will allow us to ignore low       */
  servoChangeRate[servo1] = 2;                                /* readings that keep our robot in perpetual motion. */

  while(true)                            // Infinite loop:
  {
    getJoystickSettings(joystick);
    if(abs(joystick.joy1_y1) > threshold)   // If the right analog stick's Y-axis readings are either above or below the threshold:
    {
      motor[motorD] = joystick.joy1_y1 / 2;         // Motor B is assigned a power level equal to the right analog stick's Y-axis reading.
    }
    else                                    // Else if the readings are within the threshold:
    {
      motor[motorD] = 0;                        // Motor B is stopped with a power level of 0.
    }


    if(abs(joystick.joy1_y1) > threshold)   // If the left analog stick's Y-axis readings are either above or below the threshold:
    {
      motor[motorE] = joystick.joy1_y1 / 2;         // Motor C is assigned a power level equal to the left analog stick's Y-axis reading.
    }
    else                                    // Else if the readings are within the threshold:
    {
      motor[motorE] = 0;                        // Motor C is stopped with a power level of 0.
    }

    if(abs(joystick.joy1_x1) > threshold)
    {
      motor[motorE] -= joystick.joy1_x1 / 2;
      motor[motorD] += joystick.joy1_x1 / 2;

      if(abs(joystick.joy1_y1) < 30)
      {
        if(joystick.joy1_x1 < 0)
        {
          motor[motorE] = -100;
          motor[motorD] = 100;
        }
        else
        {
          motor[motorE] = 100;
          motor[motorD] = -100;
        }
      }
    }
    if(joy1Btn(1))
    {
      servo[servo1] = 180;
    }
    if(joy1Btn(2))
    {
      servo[servo1] = 0;
    }
    wait1Msec(100);
  }
}
