#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     snsAccel,            sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     driveLeft,     tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     driveRight,    tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     arm1Motor,     tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     arm2Motor,     tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     arm3Motor,     tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     arm4Motor,     tmotorNormal, PIDControl, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    pinStabilizer,        tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Motor Power
#define mtrDriveLeftPow motor[driveLeft]
#define mtrDriveRightPow motor[driveRight]
#define mtrArm1Pow motor[arm1Motor]
#define mtrArm2Pow motor[arm2Motor]
#define mtrArm3Pow motor[arm3Motor]
#define mtrArm4Pow motor[arm4Motor]

//Motor Encoders
#define mtrDriveLeftEnc nMotorEncoder[driveLeft]
#define mtrDriveRightEnc nMotorEncoder[driveRight]
#define mtrArm1Enc nMotorEncoder[arm1Motor]
#define mtrArm2Enc nMotorEncoder[arm2Motor]
#define mtrArm3Enc nMotorEncoder[arm3Motor]
#define mtrArm4Enc nMotorEncoder[arm4Motor]

//Motor Encoder Targets
#define mtrDriveLeftTarget nMotorEncoderTarget[driveLeft]
#define mtrDriveRightTarget nMotorEncoderTarget[driveRight]
#define mtrArm1Target nMotorEncoderTarget[arm1nMotorEncoderTarget]
#define mtrArm2Target nMotorEncoderTarget[arm2nMotorEncoderTarget]
#define mtrArm3Target nMotorEncoderTarget[arm3nMotorEncoderTarget]
#define mtrArm4Target nMotorEncoderTarget[arm4nMotorEncoderTarget]

//Servo
#define srvPinStabilizer servo[pinStabilizer]

#define updateHTACValues 	HTACreadAllAxes(snsAccel, xVal, yVal, zVal)
#define htXVal (xVal-snsValAccelThreshold)

#include "HTAC-driver.h"

int snsValAccelThreshold = 0;
int xVal, yVal, zVal, stupidRobotCDoestWork;

void levelPins()
{
  /*bool continuable = true;
  updateHTACValues;
        PlaySound(soundDownwardTones);
      while(bSoundActive) {}
  if(abs(htZVal) > 5)
  {
    if(htZVal < 0)
    {
      srvPinStabilizer = 0;
    }
    else
    {
      srvPinStabilizer = 255;
    }
    while(continuable)
    {
      updateHTACValues;
      if(abs(htZVal) < 50)
      {
        srvPinStabilizer = 127;
        continuable = false;
      }
      nxtDisplayTextLine(4, ""+htZVal);
    }
  }*/
  updateHTACValues;
  while(htXVal > 0)
  {
    srvPinStabilizer = 255;
    nxtDisplayTextLine(4, ""+htXVal);
    nxtDisplayTextLine(5, ""+xVal);
  }
  srvPinStabilizer = 127;
  wait1Msec(1000);
}

task main()
{
  eraseDisplay();
  //srvPinStabilizer = 255;
  //wait1Msec(1000);
  //srvPinStabilizer = 127;
  //PlaySound(soundException);
  //while(true) {}

	wait1Msec(2000); PlaySound(soundFastUpwardTones);
  updateHTACValues;
  snsValAccelThreshold = xVal;
  nxtDisplayTextLine(3, ""+snsValAccelThreshold);
  ClearTimer(T1);
  while(time1(T1) < 3000)
  {
    nVolume = 2;
    PlaySound(soundLowBuzzShort);
    while(bSoundActive) {}
  }
  levelPins();
}
