#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     arm0,          tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     ballCup,       tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     arm2,          tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     arm1,          tmotorNormal, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    ballCatch,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    crateBinding,         tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define mDriveRight motor[driveRight]
#define mDriveLeft motor[driveLeft]
#define mBallCup motor[ballCup]
#define mArm0 motor[arm0]
#define mArm1 motor[arm1]
#define mArm2 motor[arm2]
#define sCrateBinding servo[crateBinding]
#define sBallCatch servo[ballCatch]

#define servoForward 0
#define servoBackward 255
#define servoHalt 128

#define servoLocked 255
#define servoUnlocked 0

#include "UpdatedJoystickDriver.c"


//Version 1.3

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}

task main()
{
  initializeRobot();
  //waitForStart();

  int threshold = 10;             /* Int 'threshold' will allow us to ignore low       */
  float sensetivity = .8;
  int ud = 1;
  int fix = 1;

  while(true)                            // Infinite loop:
  {
    if(joy1Btn(1)) {sensetivity = .8; }
    if(joy1Btn(3)) {sensetivity = 3.5; }

    getJoystickSettings(joystick);
    if(abs(joystick.joy1_y1) > threshold)   // If the right analog stick's Y-axis readings are either above or below the threshold:
    {
      motor[motorD] = joystick.joy1_y1 / (2*sensetivity);         // Motor B is assigned a power level equal to the right analog stick's Y-axis reading.
    }
    else                                    // Else if the readings are within the threshold:
    {
      motor[motorD] = 0;                        // Motor B is stopped with a power level of 0.
    }


    if(abs(joystick.joy1_y1) > threshold)   // If the left analog stick's Y-axis readings are either above or below the threshold:
    {
      motor[motorE] = joystick.joy1_y1 / (2*sensetivity);         // Motor C is assigned a power level equal to the left analog stick's Y-axis reading.
    }
    else                                    // Else if the readings are within the threshold:
    {
      motor[motorE] = 0;                        // Motor C is stopped with a power level of 0.
    }

    if(abs(joystick.joy1_x1) > threshold)
    {
      motor[motorE] -= joystick.joy1_x1 / (2*sensetivity);
      motor[motorD] += joystick.joy1_x1 / (2*sensetivity);

      if(abs(joystick.joy1_y1) < 30)
      {
        if(joystick.joy1_x1 < 0)
        {
          motor[motorE] = (100/sensetivity); 	//Divide by zero
          motor[motorD] = (-100/sensetivity);
        }
        else
        {
          motor[motorE] = (-100/sensetivity);
          motor[motorD] = (100/sensetivity);
        }
      }
    }

    int buttonTemp = joystick.joy1_Buttons;
    //nxtDisplayTextLine(3, ""+buttonTemp);
    if(buttonTemp >= 2048) /*R3*/ {buttonTemp -= 2048;}
    if(buttonTemp >= 1024) /*L3*/ {buttonTemp -= 1024;}
    if(buttonTemp >= 512) /*Start*/ {buttonTemp -= 512;}
    if(buttonTemp >= 256) /*Back*/ {buttonTemp -= 256;}
    if(buttonTemp >= 128) /*RT*/ {buttonTemp -= 128;}
    if(buttonTemp >= 64) /*LT*/ {buttonTemp -= 64;}
    if(buttonTemp >= 32) /*RB*/ {buttonTemp -= 32;}
    if(buttonTemp >= 16) /*LB*/ {buttonTemp -= 16;}
    if(buttonTemp >= 8) /*Y (4) (Top)*/ {buttonTemp -= 8;}
    if(buttonTemp >= 4) /*B (3) (Right)*/ {buttonTemp -= 4;}
    if(buttonTemp >= 2) /*A (2) (Bottom)*/ {buttonTemp -= 2;}
    if(buttonTemp >= 1) /*X (1) (Left)*/
    {
      buttonTemp -= 1;

    } else {

    }
  }
  wait1Msec(100);
}
