#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,                    sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorE,        tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorD,        tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     arm0,          tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     ballCup,       tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     arm2,          tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     arm1,          tmotorNormal, PIDControl, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    crateBinding,         tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define mDriveRight motor[driveRight]
#define mDriveLeft motor[driveLeft]
#define mBallCup motor[ballCup]
#define mArm0 motor[arm0]
#define mArm1 motor[arm1]
#define mArm2 motor[arm2]
#define sCrateBinding servo[crateBinding]
#define sBallCatch servo[ballCatch]


#define servoForward 100
#define servoBackward -100
#define servoHalt 0

#define servoLocked 255
#define servoUnlocked 0

#include "JoystickDriverX.c"
//#include "SourceCode31-2Func.c"

//Version 1.3

#define enterButton (nNxtButtonPressed == 3)
#define leftArrow (nNxtButtonPressed == 2)
#define rightArrow (nNxtButtonPressed == 1)

#define angleArm0 ((nMotorEncoder[arm0]/9)/4)
#define angleArm1 ((nMotorEncoder[arm1]/6)/4)

void funcOne()
{
  servo[crateBinding] = 127;
  wait1Msec(500);
  //wait1Msec(21000);
  /*while(!enterButton) {
	  if(leftArrow) {motor[arm1] = -40;} else {motor[arm1] = 0;}
	  if(rightArrow) {motor[arm0] = -80;} else {motor[arm0] = 0;}
  }*/
  nMotorEncoder[arm0] = 0;
  nMotorEncoder[arm1] = 0;
  while(true)
  {
    nxtDisplayTextLine(3, "B: "+angleArm0);
    nxtDisplayTextLine(4, "T: "+angleArm1);
    nxtDisplayTextLine(5, "Th: "+(angleArm1-angleArm0));
    nxtDisplayTextLine(6, "Sv: "+(255*2*(angleArm1-angleArm0)/180));
    int angleVar = (angleArm1-angleArm0);
    if(angleArm0 < 17) {angleVar += angleArm0;} else {angleVar += 17;}
    servo[crateBinding] = 127-(2*(255*(angleVar)/180));

    if(angleArm0 < 150)
    {
      if(angleArm1 > 117 && angleArm0 > 90) {motor[arm0] = 25;} else {motor[arm0] = 90;}
    } else {motor[arm0] = 0;}

    if(angleArm1 < 131)
    {
      if(angleArm0 > 22) {motor[arm1] = 42;} else {motor[arm1] = 0;}
    } else {motor[arm1] = 0;}

    //while(!enterButton) {
	    //if(leftArrow) {motor[arm1] = 40} else {motor[arm1] = 0;}
	    //if(rightArrow) {motor[arm0] = 80} else {motor[arm0] = 0;}
    //}
  }
}

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
  nMotorEncoder[arm1] = 0;
  return;
}

task main()
{
      int buttonTemp = joystick.joy1_Buttons;
    //nxtDisplayTextLine(3, ""+buttonTemp);
    //nxtDisplayTextLine(4, ""+buttonTemp);
    //nxtDisplayTextLine(2, ""+joystick.joy1_y1);
    //nxtDisplayTextLine(3, ""+joystick.joy1_x1);
    bool rTPressed = false;
  //motor[ballCup] = 100;
  //while(true);
  sCrateBinding = 127;
  int sVal = 1270;
  initializeRobot();
  //waitForStart();

  int threshold = 10;             /* Int 'threshold' will allow us to ignore low       */
  float sensetivity = 1;
  int ud = 1;
  int fix = 1;
  int crateBindingBaseVal = 127;
  //funcOne();

  int joy1Y1_LV = 0;
  int joy1X1_LV = 0;
  int joy1Y2_LV = 0;

  while(true)                            // Infinite loop:
  {
    if(joystick.joy1_y2 != 0) {joy1Y1_LV = joystick.joy1_y1;}
    if(joystick.joy1_y2 != 0) {joy1X1_LV = joystick.joy1_x1;}
    if(joystick.joy1_y2 != 0) {joy1Y2_LV = joystick.joy1_y2;}

    //if(joy1Btn(1)) {sensetivity = .8; }
    //if(joy1Btn(3)) {sensetivity = 3.5; }

    getJoystickSettings(joystick);
    if(((abs(joystick.joy1_y1) > threshold)))   // If the right analog stick's Y-axis readings are either above or below the threshold:
    {
      motor[motorD] = joystick.joy1_y1 / (2*sensetivity);
      nxtDisplayTextLine(1, ""+joystick.joy1_y1);// Motor B is assigned a power level equal to the right analog stick's Y-axis reading.
      nxtDisplayTextLine(2, "> thresh");
      nxtDisplayTextLine(3, "-");
    }
    else                                    // Else if the readings are within the threshold:
    {
      nxtDisplayTextLine(1, ""+joystick.joy1_y1);
      motor[motorD] = 0;
      nxtDisplayTextLine(3, "< thresh"); // Motor B is stopped with a power level of 0.
      nxtDisplayTextLine(2, "-");
    }


    if(abs(joystick.joy1_y1) > threshold)   // If the left analog stick's Y-axis readings are either above or below the threshold:
    {
      motor[motorE] = joystick.joy1_y1 / (2*sensetivity);         // Motor C is assigned a power level equal to the left analog stick's Y-axis reading.
    }
    else                                    // Else if the readings are within the threshold:
    {
      //motor[motorE] = 0;                        // Motor C is stopped with a power level of 0.
    }

    if(abs(joystick.joy1_x1) > threshold)
    {
      motor[motorE] -= joystick.joy1_x1 / (2*sensetivity);
      motor[motorD] += joystick.joy1_x1 / (2*sensetivity);

      if(abs(joystick.joy1_y1) < 30)
      {
        if(joystick.joy1_x1 < 0)
        {
          motor[motorE] = (100/sensetivity); 	//Divide by zero
          motor[motorD] = (-100/sensetivity);
        }
        else
        {
          motor[motorE] = (-100/sensetivity);
          motor[motorD] = (100/sensetivity);
        }
      }
    }

    //if(abs(joystick.joy1_y2) > 5)
    //{
    //  mArm1 = joystick.joy1_y2*(50/128);
    //} else {/*mArm1 = 0;*/}

    nxtDisplayTextLine(4, ""+(nMotorEncoder[arm1]));

    buttonTemp = joystick.joy1_Buttons;
    //nxtDisplayTextLine(3, ""+buttonTemp);
    //nxtDisplayTextLine(4, ""+buttonTemp);
    //nxtDisplayTextLine(2, ""+joystick.joy1_y1);
    //nxtDisplayTextLine(3, ""+joystick.joy1_x1);
     rTPressed = false;
    if(buttonTemp >= 2048) /*R3*/ {buttonTemp -= 2048;}
    if(buttonTemp >= 1024) /*L3*/ {buttonTemp -= 1024;}
    if(buttonTemp >= 512) /*Start*/ {buttonTemp -= 512; sensetivity = 3.5;}
    if(buttonTemp >= 256) /*Back*/ {buttonTemp -= 256; sensetivity = .3;}
    if(buttonTemp >= 128) /*RT*/ {buttonTemp -= 128; rTPressed = true;} else {rTPressed = false;}
    if(buttonTemp >= 64) /*LT*/
    {
      buttonTemp -= 64;
      if(rTPressed)
      {
	      funcOne();
      }
    }
    if(buttonTemp >= 32) /*RB*/ {buttonTemp -= 32; sVal += 1;}
    if(buttonTemp >= 16) /*LB*/ {buttonTemp -= 16; sVal -= 1;}
    if(sVal > 2550) sVal = 2550;
    if(sVal < 0) sVal = 0;
    if(buttonTemp >= 8) /*Y (4) (Top)*/ {buttonTemp -= 8; motor[motorA] = servoForward;} else {motor[motorA] = servoHalt;}
    if(buttonTemp >= 4) /*B (3) (Right)*/ {buttonTemp -= 4;}
    if(buttonTemp >= 2) /*A (2) (Bottom)*/
    {
      buttonTemp -= 2;
      nMotorEncoder[ballCup] = 0;
      while(abs(nMotorEncoder[ballCup]) < 725)
		  {
		    mBallCup = -40;
		  }
		  mBallCup = 0;
		  int revVal = abs(nMotorEncoder[ballCup]);
		  wait1Msec(250);
		  while(abs(nMotorEncoder[ballCup]) > 150)
		  {
		    mBallCup = 15;
		    nxtDisplayTextLine(3,""+nMotorEncoder[ballCup]);
		  }
		  mBallCup = 0;
		  nxtDisplayTextLine(3,""+nMotorEncoder[ballCup]);
    }
    if(buttonTemp >= 1) /*X (1) (Left)*/ {buttonTemp -= 1;}


    int angleVar = (angleArm1-angleArm0);
    if(angleArm0 < 17) {angleVar += angleArm0;} else {angleVar += 17;}
    servo[crateBinding] = crateBindingBaseVal-(2*(255*(angleVar)/180));
  }
  wait1Msec(100);
}
