#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     motorsLeft,        tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorsRight,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorArm,      tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorNormal, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

float l = 0;
float r = 0;
float null;

task main()
{
	float xPowerRaw = 0;
	float yPowerRaw = 0;
	float yPower = 0;
	float xPower = 0;
	float sensitivityY = 1;
	float sensitivityX = 1;

	while(true)
	{
		xPowerRaw = joystick.joy1_x1;
		yPowerRaw = joystick.joy1_y1;

		float motorsLeftVar = 0;
		float motorsRightVar = 0;

    motorsLeftVar = 100*yPowerRaw/128 + xPowerRaw/(yPowerRaw;
		motorsRightVar = 100*yPowerRaw/128 - xPowerRaw/2;

	  motor[motorsLeft] = motorsLeftVar;
	  motor[motorsRight] = motorsRightVar;

		//input other button-based controls.
	}
}
