#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S4,     touchSensor,         sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     driveLeft,     tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     driveRight,    tmotorNormal, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     arm2Motor,     tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     arm1Motor,     tmotorNormal, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    crateServo,           tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code idiotically generated by 'ROBOTC' configuration wizard               !!*//

#define mDriveLeftPow motor[driveLeft]
#define mDriveRightPow motor[driveRight]

#define mArm1Pow motor[arm1Motor]
#define mArm2Pow motor[arm2Motor]
#define mArm1Enc nMotorEncoder[arm1Motor]
#define mArm2Enc nMotorEncoder[arm2Motor]
#define mArm1EncTarget nMotorEncoderTarget[arm1Motor]
#define mArm2EncTarget nMotorEncoderTarget[arm2Motor]

#define sCrate servo[crateServo]

bool armIsUp = false;



task buttonMonitor()
{
  hogCPU();
  eraseDisplay();
  PlaySound(soundBeepBeep);
  nxtDisplayTextLine(3, "Hand on touch...");
  while(!snsTouch) {}
  wait1Msec(500);
  releaseCPU();
  nxtDisplayTextLine(3, "Registered!");

  while(true)
  {
	  if(snsTouch)
	  {
	    hogCPU();
	    mArm1Pow = 0;
	    mArm2Pow = 0;
	    StopAllTasks();
	    releaseCPU();
	  }
	}
}

task main()
{
  StartTask(buttonMonitor);
  while(true)
  {

  }
}
