#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,                    sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define enterButton (nNxtButtonPressed == 3)
#define leftArrow (nNxtButtonPressed == 2)
#define rightArrow (nNxtButtonPressed == 1)

task main()
{
  PlaySound(soundFastUpwardTones);
  bool bottomMotor = true;
  while(true)
  {
    switch(nNxtButtonPressed)
    {
    case 1:
      if(bottomMotor) {motor[motorD] = -30;} else {motor[motorE] = 40;}
      while(nNxtButtonPressed == 1) {}
      break;
    case 2:
      if(bottomMotor) {motor[motorD] = 30;} else {motor[motorE] = -40;}
      while(nNxtButtonPressed == 2) {}
      break;
    case 3:
      bottomMotor = !bottomMotor;
      while(nNxtButtonPressed == 3) {}
      break;
    default:
      motor[motorD] = 0;
      motor[motorE] = 0;
      break;
    }
  }
}
