#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,                    sensorI2CMuxController)
#pragma config(Motor,  motorA,          ,              tmotorNormal, openLoop, encoder)
#pragma config(Motor,  motorB,          ,              tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorE,        tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorD,        tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     arm0,          tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     ballCup,       tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     arm2,          tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     arm1,          tmotorNormal, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    ballCatch,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    crateBinding,         tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "UpdatedJoystickDriver.c"

void SMAN(tMotor sM1, float targetRotationSpeed, float gearRatio1, tMotor sM2, float targetRotationSpeed2, float gearRatio2, int initSpeed)
{
  ClearTimer(T2);
  nMotorEncoder[sM1] = 0;
  nMotorEncoder[sM2] = 0;
  float currentM1Speed = initSpeed;
  float currentM2Speed = -initSpeed;
  motor[sM1] = initSpeed;
  motor[sM2] = -initSpeed;
  wait1Msec(1500);

  while(true)
  {
    float crappyVariable = nMotorEncoder[sM1] / gearRatio1;
    float crappyVariable2 = nMotorEncoder[sM2] / gearRatio2;
    float stupidRobotCDoesntWork = time1[T2];
    stupidRobotCDoesntWork = stupidRobotCDoesntWork/4;
    float stupidRobotCDoesntWork2 = nMotorEncoder[sM1];
    float thingamabobber = stupidRobotCDoesntWork2/stupidRobotCDoesntWork;

    float stupidRobotCDoesntWork3 = time1[T2];
    stupidRobotCDoesntWork3 = stupidRobotCDoesntWork3/4;
    float stupidRobotCDoesntWork4 = abs(nMotorEncoder[sM2]);
    float thingamabobber2 = stupidRobotCDoesntWork4/stupidRobotCDoesntWork3;

    if(stupidRobotCDoesntWork != stupidRobotCDoesntWork3) PlaySound(soundFastUpwardTones);

    nxtDisplayTextLine(3, ""+thingamabobber2);
    nxtDisplayTextLine(4, ""+currentM2Speed);
    nxtDisplayTextLine(2, "OK: "+currentM1Speed);
    nxtDisplayTextLine(1, ""+thingamabobber);

    nxtDisplayTextLine(6, ""+time1[T2]);
    nxtDisplayTextLine(7, ""+time10[T2]);

    //nxtDisplayTextLine(3, ""+time1[T1]);
    wait1Msec(4);
    while(nNxtButtonPressed == 3);
    if(abs(thingamabobber) > abs(targetRotationSpeed)) {currentM1Speed -= .05; wait1Msec(25);}
    if(abs(thingamabobber) < abs(targetRotationSpeed)) {currentM1Speed += .05; wait1Msec(25);}

    if(abs(thingamabobber2) > abs(targetRotationSpeed2)) {currentM2Speed +=.05; wait1Msec(25);}
    if(abs(thingamabobber2) < abs(targetRotationSpeed2)) {currentM2Speed -= .05; wait1Msec(25);}

    motor[sM1] = currentM1Speed;
    motor[sM2] = currentM2Speed;

    if(time1[T2] > 20)
    {
      //ClearTimer(T1);
      nMotorEncoder[sM2] = 0;
      //wait1Msec(150);
      if(abs(thingamabobber2) > abs(targetRotationSpeed2)) {currentM2Speed += 0.4; wait1Msec(25);}
      if(abs(thingamabobber2) < abs(targetRotationSpeed2)) {currentM2Speed -= 0.4; wait1Msec(25);}
    }

    if(time1[T2] > 20)
    {
      ClearTimer(T2);
      nMotorEncoder[sM1] = 0;
      wait1Msec(150);
      if(thingamabobber > targetRotationSpeed) {currentM1Speed -= 0.4; wait1Msec(25);}
      if(thingamabobber < targetRotationSpeed) {currentM1Speed += 0.4; wait1Msec(25);}
      //PlaySound(soundDownwardTones);
    }

    if(abs(crappyVariable) > abs(crappyVariable2) && abs(abs(crappyVariable) - abs(crappyVariable2)) > 10) currentM2Speed += .1;
    if(abs(crappyVariable) < abs(crappyVariable2) && abs(abs(crappyVariable) - abs(crappyVariable2)) > 10) currentM2Speed -= .1;
  }
}

void SMAN(tMotor sM1, float targetRotationSpeed, int initSpeed) //DO NOT CHANGE
{
  ClearTimer(T1);
  nMotorEncoder[sM1] = 0;
  float currentM1Speed = initSpeed;
  motor[sM1] = initSpeed;
  wait1Msec(1500);

  while(true)
  {
    float stupidRobotCDoesntWork = time1[T1];
    stupidRobotCDoesntWork = stupidRobotCDoesntWork/4;
    float stupidRobotCDoesntWork2 = nMotorEncoder[sM1];

    float thingamabobber = stupidRobotCDoesntWork2/stupidRobotCDoesntWork;
    //nxtDisplayTextLine(4, ""+thingamabobber);
    //nxtDisplayTextLine(2, ""+currentM1Speed);
    //nxtDisplayTextLine(3, ""+time1[T1]);
    wait1Msec(4);
    while(nNxtButtonPressed == 3);
    if(thingamabobber > targetRotationSpeed) {currentM1Speed -= .05; wait1Msec(25);}
    if(thingamabobber < targetRotationSpeed) {currentM1Speed += .05; wait1Msec(25);}

    motor[sM1] = currentM1Speed;
    if(time1[T1] > 20)
    {
      ClearTimer(T1);
      nMotorEncoder[sM1] = 0;
      wait1Msec(150);
      if(thingamabobber > targetRotationSpeed) {currentM1Speed -= 0.4; wait1Msec(25);}
      if(thingamabobber < targetRotationSpeed) {currentM1Speed += 0.4; wait1Msec(25);}
    }
  }
}

task main()
{

  eraseDisplay();
  while(true)
  {
    if(joy1Btn(6)) PlaySound(soundBeepBeep);
    if(joy1Btn(7)) PlaySound(soundBlip);
    if(joy1Btn(6) && joy1Btn(7)) SMAN(motorA, 1.75, motorB, 1.75, 20);
  }
}
