#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,                    sensorI2CMuxController)
#pragma config(Motor,  motorA,          ,              tmotorNormal, openLoop, encoder)
#pragma config(Motor,  motorB,          ,              tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorE,        tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorD,        tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     arm0,          tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     ballCup,       tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     arm2,          tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     arm1,          tmotorNormal, PIDControl, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    ballCatch,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    crateBinding,         tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define enterButton (nNxtButtonPressed == 3)
#define leftArrow (nNxtButtonPressed == 2)
#define rightArrow (nNxtButtonPressed == 1)

#define mDriveRight motor[driveRight]
#define mDriveLeft motor[driveLeft]
#define mBallCup motor[ballCup]
#define mArm0 motor[arm0]
#define mArm1 motor[arm1]
#define mArm2 motor[arm2]
#define sCrateBinding servo[crateBinding]
#define sBallCatch servo[ballCatch]

#include "UpdatedJoystickDriver.c"

void SMAN(tMotor sM1, float targetRotationSpeed, int initSpeed, tMotor sM2, float targetRotationSpeed2, int initSpeed2)
{
  motor[sM1] = 100*initSpeed/abs(initSpeed);
  //motor[sM2] = 100*initSpeed2/abs(initSpeed2);
  wait1Msec(50);
  motor[sM1] = 0;
  motor[sM2] = 0;
  ClearTimer(T2);
  nMotorEncoder[sM1] = 0;
  nMotorEncoder[sM2] = 0;
  float currentM1Speed = initSpeed;
  float currentM2Speed = initSpeed2;
  motor[sM1] = initSpeed;
  motor[sM2] = initSpeed2;
  int initSpeedPositive = initSpeed/abs(initSpeed);
  int initSpeedPositive2 = initSpeed2/abs(initSpeed2);
  //wait1Msec();

  //bool stopSMAN = false;
  while(true)
  {
    float stupidRobotCDoesntWork = time1[T2];
    stupidRobotCDoesntWork = stupidRobotCDoesntWork/4;
    float stupidRobotCDoesntWork2 = nMotorEncoder[sM1];
    float thingamabobber = stupidRobotCDoesntWork2/stupidRobotCDoesntWork;

    float stupidRobotCDoesntWork3 = time1[T2];
    stupidRobotCDoesntWork3 = stupidRobotCDoesntWork3/4;
    float stupidRobotCDoesntWork4 = abs(nMotorEncoder[sM2]);
    float thingamabobber2 = stupidRobotCDoesntWork4/stupidRobotCDoesntWork3;

    if(stupidRobotCDoesntWork != stupidRobotCDoesntWork3) PlaySound(soundFastUpwardTones);

    //nxtDisplayTextLine(3, ""+thingamabobber2);
    //nxtDisplayTextLine(4, ""+currentM2Speed);
    //nxtDisplayTextLine(2, "OK: "+currentM1Speed);
    //nxtDisplayTextLine(1, ""+thingamabobber);
    //nxtDisplayTextLine(6, ""+time1[T2]);
    //nxtDisplayTextLine(7, ""+time10[T2]);
    //nxtDisplayTextLine(3, ""+time1[T1]);
    nxtDisplayTextLine(3, ""+nMotorEncoder[sM1]);
    nxtDisplayTextLine(4, ""+nMotorEncoder[sM2]);
    nxtDisplayTextLine(5, ""+motor[sM1]);
    nxtDisplayTextLine(6, ""+motor[sM2]);

    wait1Msec(4);
    while(nNxtButtonPressed == 3);
    if(abs(thingamabobber) > abs(targetRotationSpeed)) {currentM1Speed -= .5; wait1Msec(25);}
    if(abs(thingamabobber) < abs(targetRotationSpeed)) {currentM1Speed += .5; wait1Msec(25);}

    if(abs(thingamabobber2) > abs(targetRotationSpeed2)) {currentM2Speed +=.5; wait1Msec(25);}
    if(abs(thingamabobber2) < abs(targetRotationSpeed2)) {currentM2Speed -= .5; wait1Msec(25);}

    motor[sM1] = currentM1Speed;
    motor[sM2] = currentM2Speed;

    if(time1[T2] > 20)
    {
      //ClearTimer(T1);
      nMotorEncoder[sM2] = 0;
      //wait1Msec(150);
      if(abs(thingamabobber2) > abs(targetRotationSpeed2)) {currentM2Speed += 2; wait1Msec(25);}
      if(abs(thingamabobber2) < abs(targetRotationSpeed2)) {currentM2Speed -= 2; wait1Msec(25);}
    }

    if(time1[T2] > 20)
    {
      ClearTimer(T2);
      nMotorEncoder[sM1] = 0;
      wait1Msec(150);
      if(thingamabobber > targetRotationSpeed) {currentM1Speed -= 0.4; wait1Msec(25);}
      if(thingamabobber < targetRotationSpeed) {currentM1Speed += 0.4; wait1Msec(25);}
      //PlaySound(soundDownwardTones);
    }
    motor[sM1] = currentM1Speed;
    motor[sM2] = currentM2Speed;

    nxtDisplayTextLine(3, ""+motor[sM1]);
    nxtDisplayTextLine(4, ""+motor[sM2]);

    if(abs(nMotorEncoder[sM2]) > abs(nMotorEncoder[sM1])*(3/4)) currentM2Speed += .5;
    if(abs(nMotorEncoder[sM2]) < abs(nMotorEncoder[sM1])*(3/4)) currentM2Speed -= .5;
    //if(!enterButton) stopSMAN = true;
  }
}

void SMAN(tMotor sM1, float targetRotationSpeed, int initSpeed) //DO NOT CHANGE
{
  ClearTimer(T1);
  nMotorEncoder[sM1] = 0;
  float currentM1Speed = initSpeed;
  motor[sM1] = initSpeed;
  wait1Msec(1500);
  int initSpeedPositive = initSpeed/abs(initSpeed);

  while(true)
  {
    float stupidRobotCDoesntWork = time1[T1];
    stupidRobotCDoesntWork = stupidRobotCDoesntWork/4;
    float stupidRobotCDoesntWork2 = nMotorEncoder[sM1];

    float thingamabobber = stupidRobotCDoesntWork2/stupidRobotCDoesntWork;
    nxtDisplayTextLine(4, ""+thingamabobber);
    nxtDisplayTextLine(2, ""+currentM1Speed);
    nxtDisplayTextLine(3, ""+time1[T1]);
    wait1Msec(4);
    while(nNxtButtonPressed == 3);
    if(thingamabobber > targetRotationSpeed) {currentM1Speed -= .5*initSpeedPositive; wait1Msec(25);}
    if(thingamabobber < targetRotationSpeed) {currentM1Speed += .5*initSpeedPositive; wait1Msec(25);}

    motor[sM1] = currentM1Speed;
    if(time1[T1] > 20)
    {
      ClearTimer(T1);
      nMotorEncoder[sM1] = 0;
      wait1Msec(150);
      if(thingamabobber > targetRotationSpeed) {currentM1Speed -= 2*initSpeedPositive; wait1Msec(25);}
      if(thingamabobber < targetRotationSpeed) {currentM1Speed += 2*initSpeedPositive; wait1Msec(25);}
    }
  }
}

void resetBase()
{
  nVolume = 4;
  PlaySound(soundFastUpwardTones);
  //bool bottomMotor = true;
  while(!enterButton) {
	  if(leftArrow) {motor[arm1] = -40} else {motor[arm1] = 0;}
	  if(rightArrow) {motor[arm0] = -80} else {motor[arm0] = 0;}
  }
}

/*void moveSimul(tMotor m1, tMotor m2, int startSpeed1, int startSpeed2, float gearRatio)
{
  motor[m1] = startSpeed1;
  motor[m2] = startSpeed2;
  nMotorEncoder[m1] = 0;
  nMotorEncoder[m2] = 0;
  while(true)
  {
    float diffBtwnEncVal = nMotorEncoder[m2] - nMotorEncoder[m1]*gearRatio;
    if(diffBtwnEncVal > 0)
    {
      motor[m1] = motor[m1] +
    }
    if(diffBtwnEncVal < 0)
  }
}*/

void armMan(int initPow0, int initPow1)
{
  nMotorEncoder[arm0] = 0;
  nMotorEncoder[arm1] = 0;
  float currentPow0 = initPow0;
  float currentPow1 = initPow1;
  while(true)
  {
    mArm0 = currentPow0;
    mArm1 = currentPow1;
    long bottomEnc = abs(nMotorEncoder[arm0]/*16*/);
    long topEnc = abs(nMotorEncoder[arm1]*2/*12*/);
    long difference = abs(bottomEnc - topEnc);
    if(bottomEnc > topEnc) {currentPow1 += .01*(sqrt(difference/100) + 1); nxtDisplayTextLine(6, "INCREASE");}
    if(bottomEnc < topEnc) {currentPow1 -= .01*(sqrt(difference/100) + 1); nxtDisplayTextLine(6, "DECREASE");}
    nxtDisplayTextLine(3, ""+currentPow1);
    nxtDisplayTextLine(4, ""+bottomEnc);
    nxtDisplayTextLine(5, ""+topEnc);
    nxtDisplayTextLine(7, ""+(bottomEnc-topEnc));
    //wait1Msec(4);
  }
}

task main()
{
  sCrateBinding = 255;
  /*resetBase();
  while(true)
  {
    nxtDisplayTextLine(2, ""+nMotorEncoder[arm0]);
    nxtDisplayTextLine(3, ""+nMotorEncoder[arm1]);
    while(leftArrow) {motor[arm0] = -40; motor[arm1] = -30;}
	  while(rightArrow) {motor[arm0] = 80; motor[arm1] = 15;}
	  motor[arm0] = 0; motor[arm1] = 0;
  }*/
  //motor[arm1] = -50; wait1Msec(1500);
  resetBase();
  PlaySound(soundBeepBeep); while(bSoundActive);
  PlaySound(soundBeepBeep); while(bSoundActive);
  PlaySound(soundBeepBeep); while(bSoundActive);
  armMan(80,10);
  //SMAN(arm0, 1.5, -15, arm1, 1.5, -15);
  //motor[arm0] = 100;
 // motor[arm1] = 20;
  //while(true);
  //while(true)
  //{
  //  if(enterButton) SMAN(arm0, 2.5, 100, arm1, 1.3, 18);
  //}
  //SMAN(arm0, 2.5, 70, arm1, .7, 20);
}
