#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,                    sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     arm2Motor,     tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     arm1Motor,     tmotorNormal, PIDControl, reversed, encoder)
#pragma config(Sensor, S4,     touchSensor,         sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define mArm1Pow motor[arm1Motor]
#define mArm2Pow motor[arm2Motor]
#define mArm1Target nMotorEncoderTarget[arm1Motor]
#define mArm2Target nMotorEncoderTarget[arm2Motor]
#define mArm1Enc nMotorEncoder[arm1Motor]
#define mArm2Enc nMotorEncoder[arm2Motor]

#define snsTouch SensorValue[touchSensor]

task buttonMonitor()
{
  hogCPU();
  eraseDisplay();
  PlaySound(soundBeepBeep);
  nxtDisplayTextLine(3, "Hand on touch...");
  while(!snsTouch) {}
  wait1Msec(500);
  releaseCPU();
  nxtDisplayTextLine(3, "Registered!");

  while(true)
  {
	  if(snsTouch)
	  {
	    hogCPU();
	    mArm1Pow = 0;
	    mArm2Pow = 0;
	    StopAllTasks();
	    releaseCPU();
	  }
	}
}

task main()
{
  StartTask(buttonMonitor);
  wait1Msec(4);
  while(true)
  {
    motor[arm2Motor] = -100;
    motor[arm1Motor] = -100;
    wait1Msec(1);
  }
}
