#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,                    sensorI2CMuxController)
#pragma config(Motor,  motorA,          ,              tmotorNormal, openLoop, encoder)
#pragma config(Motor,  motorB,          ,              tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorE,        tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorD,        tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     arm0,          tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     ballCup,       tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     arm2,          tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     arm1,          tmotorNormal, PIDControl, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    ballCatch,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    crateBinding,         tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define enterButton (nNxtButtonPressed == 3)
#define leftArrow (nNxtButtonPressed == 2)
#define rightArrow (nNxtButtonPressed == 1)

#define angleArm0 ((nMotorEncoder[arm0]/9)/4)
#define angleArm1 ((nMotorEncoder[arm1]/6)/4)

//#include "JoystickDriver.c"

void funcOne()
{
  servo[crateBinding] = 127;
  wait1Msec(500);
  //wait1Msec(21000);
  while(!enterButton) {
	  if(leftArrow) {motor[arm1] = -40;} else {motor[arm1] = 0;}
	  if(rightArrow) {motor[arm0] = -80;} else {motor[arm0] = 0;}
  }
  nMotorEncoder[arm0] = 0;
  nMotorEncoder[arm1] = 0;
  while(true)
  {
    //getJoystickSettings(joystick);
    nxtDisplayTextLine(3, "B: "+angleArm0);
    nxtDisplayTextLine(4, "T: "+angleArm1);
    nxtDisplayTextLine(5, "Th: "+(angleArm1-angleArm0));
    nxtDisplayTextLine(6, "Sv: "+(255*2*(angleArm1-angleArm0)/180));
    int angleVar = (angleArm1-angleArm0);
    if(angleArm0 < 17) {angleVar += angleArm0;} else {angleVar += 17;}
    servo[crateBinding] = 127-(2*(255*(angleVar)/180));

    if(angleArm0 < 146)
    {
      if(angleArm1 > 117 && angleArm0 > 90) {motor[arm0] = 25;} else {motor[arm0] = 90;}
    } else {motor[arm0] = 0;}

    if(angleArm1 < 131)
    {
      if(angleArm0 > 22) {motor[arm1] = 42;} else {motor[arm1] = 0;}
    } else {motor[arm1] = 0;}

    //while(!enterButton) {
	    //if(leftArrow) {motor[arm1] = 40} else {motor[arm1] = 0;}
	    //if(rightArrow) {motor[arm0] = 80} else {motor[arm0] = 0;}
    //}
  }
}

task main()
{
  funcOne();
}
