#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Motor,  mtr_S1_C1_1,     driveRight,    tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     driveLeft,     tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     arm0,          tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     ballCup,       tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     arm2,          tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     arm1,          tmotorNormal, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    ballCatch,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    crateBinding,         tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define mDriveRight motor[driveRight]
#define mDriveLeft motor[driveLeft]
#define mBallCup motor[ballCup]
#define mArm0 motor[arm0]
#define mArm1 motor[arm1]
#define mArm2 motor[arm2]
#define sCrateBinding servo[crateBinding]
#define sBallCatch servo[ballCatch]

#define servoForward 0
#define servoBackward 255
#define servoHalt 128

#define servoLocked 255
#define servoUnlocked 0

#include "UpdatedJoystickDriver.c"

task main()
{
  //StartTask(mainDriveTrain);
  bool servoIsLocked = false;
  bool buttonXIsHeld = false;
  servoChangeRate[ballCatch] = 8;
  //eraseDisplay();
  while(true)
  {
    getJoystickSettings(joystick);
    int buttonTemp = joystick.joy1_Buttons;
    nxtDisplayTextLine(3, ""+buttonTemp);
    if(buttonTemp >= 2048) /*R3*/ {buttonTemp -= 2048;}
    if(buttonTemp >= 1024) /*L3*/ {buttonTemp -= 1024;}
    if(buttonTemp >= 512) /*Start*/ {buttonTemp -= 512;}
    if(buttonTemp >= 256) /*Back*/ {buttonTemp -= 256;}
    if(buttonTemp >= 128) /*RT*/ {buttonTemp -= 128;}
    if(buttonTemp >= 64) /*LT*/ {buttonTemp -= 64;}
    if(buttonTemp >= 32) /*RB*/ {buttonTemp -= 32;}
    if(buttonTemp >= 16) /*LB*/ {buttonTemp -= 16;}
    if(buttonTemp >= 8) /*Y (4) (Top)*/ {buttonTemp -= 8;}
    if(buttonTemp >= 4) /*B (3) (Right)*/ {buttonTemp -= 4;}
    if(buttonTemp >= 2) /*A (2) (Bottom)*/ {buttonTemp -= 2;}
    if(buttonTemp >= 1) /*X (1) (Left)*/
    {
      buttonTemp -= 1;
      if(!buttonXIsHeld)
      {
        buttonXIsHeld = true;
        if(servoIsLocked)
        {
          sCrateBinding = servoUnlocked;
        } else {
          sCrateBinding = servoLocked;}
        servoIsLocked = !servoIsLocked;
      }
    } else {buttonXIsHeld = false;}
    EndTimeSlice();
  }
}
