#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,                    sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorE,        tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorD,        tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     arm0,          tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     ballCup,       tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     arm2,          tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     arm1,          tmotorNormal, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    ballCatch,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    crateBinding,         tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define mArm1Pow motor[arm0]
#define mArm2Pow motor[arm1]
#define mArm1Target nMotorEncoderTarget[arm0]
#define mArm2Target nMotorEncoderTarget[arm1]
#define mArm1Enc nMotorEncoder[arm0]
#define mArm2Enc nMotorEncoder[arm1]

#define snsTouch SensorValue[touchSensor]
#define enterButton (nNxtButtonPressed == 3)
#define leftArrow (nNxtButtonPressed == 2)
#define rightArrow (nNxtButtonPressed == 1)

//#define sCrate servo[crateServo]

#define oneDegreeInEnc 12
#define oneDegreeInServo 1.4167

#include "JoystickDriver.c"

void collapseArm()
{
  mArm1Enc = 0;
  mArm2Enc = 0;
  bool incArm1 = false;
  bool incArm2 = false;
  mArm1Pow = 20;

  mArm2Pow = -20;

  float errorTrap1_1 = 0;
  float errorTrap2_1;

  float errorTrap1_2 = 0;
  float errorTrap2_2;

  int i = 0;

  while(!(incArm1 && incArm2))
  {
    if(abs(mArm1Enc) > 150*oneDegreeInEnc && incArm1 == false)
    {
      mArm1Pow = -3;
      incArm1 = true;
    }

    if(abs(mArm2Enc) > 155*oneDegreeInEnc && incArm2 == false)
    {
      mArm2Pow = 0;
      incArm2 = true;
    }
    EndTimeSlice();
  }

  mArm1Pow = 0;
  mArm2Pow = 0;
}

void raiseArm()
{
  mArm1Enc = 0;
  mArm2Enc = 0;
  bool incArm1 = false;
  bool incArm2 = false;
  //mArm1Pow = 15;
  mArm2Pow = 30;

  int i = 0;

  while(!(incArm1 && incArm2))
  {/*
    if(abs(mArm1Enc) > 145.5*oneDegreeInEnc && incArm1 == false)
    {
      mArm1Pow = -6;
      incArm1 = true;
    }
*/
   if(abs(mArm2Enc) > 155*oneDegreeInEnc && incArm2 == false)
    {
      mArm2Pow = 5;
      incArm2 = true;
    }

    if(!incArm1) {mArm1Pow = -15;}
    //if(!incArm2) {mArm2Pow = 30;}
    EndTimeSlice();
  }

  mArm1Pow = 0;
  mArm2Pow = 0;
}
/*
void arm2Down()
{
  mArm2Enc = 0;
  mArm2Pow = 100;
  wait1Msec(10);
  mArm2Pow = 10;
  float scalar = .8222;
  while(abs(mArm2Enc) < 90*oneDegreeInEnc)
  {
    if((int)(255-(mArm2Enc/oneDegreeInEnc)*oneDegreeInServo) != 1666)
    {
      //sCrate = 255-(mArm2Enc/oneDegreeInEnc)*oneDegreeInServo;
      AddToDatalog(255-(mArm2Enc/oneDegreeInEnc)*oneDegreeInServo);
    }
    EndTimeSlice();
  }
  mArm2Pow = -2;
  wait1Msec(1000);
  //SaveNxtDatalog();
}

void arm2Up()
{
  mArm2Enc = 0;
  mArm2Pow = -100;
  wait1Msec(10);
  mArm2Pow = -40;
  float scalar = .8222;
  //float startVal = sCrate;
  nxtDisplayTextLine(1, ""+startVal);

  while(abs(mArm2Enc) < 90*oneDegreeInEnc)
  {
    if((int)(255-(mArm2Enc/oneDegreeInEnc)*oneDegreeInServo) != 1666)
    {
      sCrate = startVal+(abs(mArm2Enc)/oneDegreeInEnc)*oneDegreeInServo;
      AddToDatalog(startVal+(abs(mArm2Enc)/oneDegreeInEnc)*oneDegreeInServo);
    }
    EndTimeSlice();
  }
  mArm2Pow = -5;
  wait1Msec(1000);
  //SaveNxtDatalog();
}
*//*
task buttonMonitor()
{
  hogCPU();
  eraseDisplay();
  PlaySound(soundBeepBeep);
  nxtDisplayTextLine(3, "Hand on touch...");
  //while(!snsTouch) {}
  //PlaySound(soundShortBlip);
  //while(bSoundActive) {}
  //wait1Msec(500);
  while(!snsTouch) {}
  wait1Msec(500);
  releaseCPU();
  nxtDisplayTextLine(3, "Registered!");

  while(true)
  {
	  if(snsTouch)
	  {
	    nVolume = 4;
	    SaveNxtDatalog();
	    hogCPU();
	    mArm1Pow = 0;
	    mArm2Pow = 0;
      PlaySound(soundFastUpwardTones);
      while(bSoundActive) {}
      wait1Msec(500);
		  while(true)
		  {
		    if(snsTouch) {StopAllTasks();}
		    switch(nNxtButtonPressed)
		    {
		    case 1:
		      motor[motorD] = -30;
		      while(nNxtButtonPressed == 1) {}
		    case 2:
		      motor[motorD] = 30;
		      while(nNxtButtonPressed == 1) {}
		    default:
		      motor[motorD] = 0;
		      break;
		    }
		    nVolume = 2;
		    PlaySound(soundException);
		  }
	    StopAllTasks();
	    releaseCPU();
	  }
	}
}*/

bool servoLocked = true;
/*
void toggleServoLock()
{
  if(servoLocked)
  {
    sCrate += 30;
  }
  else
  {
    sCrate -= 30;
  }

  servoLocked = !servoLocked;
  wait1Msec(500);
}*/

void resetBase()
{
  PlaySound(soundFastUpwardTones);
  //bool bottomMotor = true;
  while(!enterButton) {
  while(leftArrow) {motor[arm0] = -40; motor[arm1] = 30;}
  while(rightArrow) {motor[arm0] = 80; motor[arm1] = -15;}
  motor[arm0] = 0; motor[arm1] = 0;}
}


task main()
{
  //while(true)
  //{
  //  StartTask(buttonMonitor);
  //  wait1Msec(2000);
  //}

  resetBase();
  raiseArm();
  wait1Msec(5000);
  collapseArm();
}
