#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,                    sensorI2CMuxController)
#pragma config(Motor,  motorA,          ,              tmotorNormal, openLoop, encoder)
#pragma config(Motor,  motorB,          ,              tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorE,        tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorD,        tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     arm0,          tmotorNormal, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     ballCup,       tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     arm2,          tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     arm1,          tmotorNormal, PIDControl, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    ballCatch,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    crateBinding,         tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,          tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define mArm1Pow motor[arm0]
#define mArm2Pow motor[arm1]
#define mArm1Target nMotorEncoderTarget[arm0]
#define mArm2Target nMotorEncoderTarget[arm1]
#define mArm1Enc nMotorEncoder[arm0]
#define mArm2Enc nMotorEncoder[arm1]

#define oneDegreeInEnc 12

#include "drivers/HTGYRO-driver.h"

task powerDownTask()
{
  hogCPU();
  mArm1Pow = 0;
  mArm2Pow = 0;;
  PlaySound(soundLowBuzz);
  while(bSoundActive) {}
  powerOff();
  releaseCPU();
}

void balanceArm()
{
  mArm1Pow = 15;
  wait1Msec(1000);
}

void collapseArm()
{
  mArm1Enc = 0;
  mArm2Enc = 0;
  bool incArm1 = false;
  bool incArm2 = false;
  mArm1Pow = 20;

  mArm2Pow = -20;

  float errorTrap1_1 = 0;
  float errorTrap2_1;

  float errorTrap1_2 = 0;
  float errorTrap2_2;

  int i = 0;

  while(!(incArm1 && incArm2))
  {
    if(abs(mArm1Enc) > 150*oneDegreeInEnc && incArm1 == false)
    {
      mArm1Pow = -3;
      incArm1 = true;
    }

    if(abs(mArm2Enc) > 155*oneDegreeInEnc && incArm2 == false)
    {
      mArm2Pow = 0;
      incArm2 = true;
    }
  }

  mArm1Pow = 0;
  mArm2Pow = 0;
}

void raiseArm()
{
  mArm1Enc = 0;
  mArm2Enc = 0;
  bool incArm1 = false;
  bool incArm2 = false;
  mArm1Pow = -30;
  mArm2Pow = 30;

  int i = 0;

  while(!(incArm1 && incArm2))
  {
    if(abs(mArm1Enc) > 150*oneDegreeInEnc && incArm1 == false)
    {
      mArm1Pow = -3;
      incArm1 = true;
    }

    if(abs(mArm2Enc) > 155*oneDegreeInEnc && incArm2 == false)
    {
      mArm2Pow = 0;
      incArm2 = true;
    }
  }

  mArm1Pow = 0;
  mArm2Pow = 0;
}

task keepLevel()
{

}

task main()
{
  raiseArm();
}
