#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,                    sensorI2CMuxController)
#pragma config(Sensor, S2,     snsAccel,            sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     driveLeft,     tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     driveRight,    tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     arm2Motor,     tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     arm1Motor,     tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     arm3Motor,     tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     arm4Motor,     tmotorNormal, PIDControl, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    pinStabilizer,        tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Motor Power
#define mtrDriveLeftPow motor[driveLeft]
#define mtrDriveRightPow motor[driveRight]
#define mtrArm1Pow motor[arm1Motor]
#define mtrArm2Pow motor[arm2Motor]
#define mtrArm3Pow motor[arm3Motor]
#define mtrArm4Pow motor[arm4Motor]

//Motor Encoders
#define mtrDriveLeftEnc nMotorEncoder[driveLeft]
#define mtrDriveRightEnc nMotorEncoder[driveRight]
#define mtrArm1Enc nMotorEncoder[arm1Motor]
#define mtrArm2Enc nMotorEncoder[arm2Motor]
#define mtrArm3Enc nMotorEncoder[arm3Motor]
#define mtrArm4Enc nMotorEncoder[arm4Motor]

//Motor Encoder Targets
#define mtrDriveLeftTarget nMotorEncoderTarget[driveLeft]
#define mtrDriveRightTarget nMotorEncoderTarget[driveRight]
#define mtrArm1Target nMotorEncoderTarget[arm1Motor]
#define mtrArm2Target nMotorEncoderTarget[arm2Motor]
#define mtrArm3Target nMotorEncoderTarget[arm3Motor]
#define mtrArm4Target nMotorEncoderTarget[arm4Motor]

//Servo
#define srvPinStabilizer servo[pinStabilizer]

void collapseArm()
{
  mtrArm1Pow = 3;

  mtrArm2Enc = 0;
  mtrArm1Enc = 0;
  mtrArm2Pow = -20;
  mtrArm1Pow = -15;
  while(abs(mtrArm1Enc) < 1475) {}
  while(abs(mtrArm2Enc) < 1750) {}
  mtrArm1Pow = 10;
  mtrArm2Pow = 0;
  wait1Msec(500);

  mtrArm3Enc = 0;
  mtrArm3Pow = -20;
  while(abs(mtrArm3Enc) < 1600) {}
  mtrArm3Pow = 0;
  wait1Msec(500);

  mtrArm1Pow = 0;
  mtrArm2Pow = 0;
  mtrArm3Pow = 0;

//  mtrArm1Enc = 0;
//  mtrArm2Pow = -20;
//  while(abs(mtrArm1Enc) < 1475) {}
//  mtrArm2Pow = 4;

}

task main()
{
  collapseArm();
  mtrArm1Enc = 0;
  mtrArm2Enc = 0;
  mtrArm3Enc = 0;
  wait1Msec(10000);
}
